import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "../globals.css";
import Footer from "../containers/footer";


const pop= Poppins({
  subsets: ["latin"],
  weight:["100","400","500","900"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <div
        className={`${pop.className} anticipated` }
      >
        {children}

      </div>
  );
}
